// template/template-react/packages/vite-react-ts/src/main.tsx
import ReactDOM from 'react-dom'
import App from './App'

import { defineSpaApp } from "spa-converter/lib/ReactSpaConverter";

export default defineSpaApp((container) => {
    return {
        mount() {
            ReactDOM.render(<App/>, container)
            console.log('react mount')
        },
        render() {
            console.log('react render')
            return ''
        },
        unmount() {
            ReactDOM.unmountComponentAtNode(container)
            console.log('react unmount')
        }
    }
})

// template/template-react/packages/vite-vue-ts/src/main.tsx
import { createApp } from 'vue'
import App from './App.vue'

import { defineSpaApp } from "spa-converter/lib/ReactSpaConverter";

export default defineSpaApp((container) => {
    const app = createApp(App)
    return {
        mount() {
            app.mount(container)
            console.log('vue mount')
        },
        render() {
            console.log('vue render')
            return ''
        },
        unmount() {
            app.unmount()
            console.log('vue unmount')
        }
    }
})
